### ISSUE TITLE
Add clap to add function to supply input file via command line argument

### ISSUE THREAD

**Issue by LMH01** [4321ba/mp3-to-nbs#1]
It would be helpful to not have the input file hard coded but instead make it possible to supply the file that should be converted by a command line argument.

**Comment by 4321ba** [comment]
100% right! Thanks for showing interest and taking the time to create a pull request! This was/is still the very beginnings of the program, but I currently do plan to revisit it as a university project next year, and if I get back to it, I'll definitely look at / analyze the pull request, and probably merge it :D (I just don't want to merge it right now because I don't really remember anything currently xd).

**Comment by 4321ba** [comment]
Thanks again ^^
